line-length = 100

[format]
quote-style = "double"
indent-style = "space"
docstring-code-format = true

[lint]
select = [
  "A",
  "AIR",
  "ANN",
  "ARG",
  "ASYNC",
  "B",
  "BLE",
  "C",
  "C4",
  # "COM",
  # "D",
  "DTZ",
  "E",
  "EM",
  "ERA",
  "EXE",
  "F",
  "FA",
  "FBT",
  "FLY",
  "FIX",
  "G",
  "I",
  "ICN",
  "INP",
  "INT",
  # "ISC",
  "N",
  "NPY",
  "PIE",
  "PGH",
  "PD",
  "PL",
  "PLE",
  "PLR",
  "PLW",
  "PT",
  "PTH",
  "PYI",
  "Q",
  "RSE",
  "RET",
  "RUF",
  "S",
  "SLF",
  "SIM",
  "TCH",
  "TD",
  "TID",
  "T10",
  "TRY",
  "W",
  "UP",
]